const EVENTS = {
    USER_LOGIN: 'user.login',
    USER_LOGGED_IN: 'user.login',
    NEW_LOGIN: 'new-login',
    USER_LOGGED_OUT: 'user.logout',
    USER_CREATED: 'user.created',
    USER_UPDATED: 'user.updated',
    USER_DELETED: 'user.deleted',
    USER_PASSWORD_CHANGED: 'user.password.changed',
    USER_PASSWORD_RESET_REQUESTED: 'user.password.reset.requested',
    USER_EMAIL_VERIFICATION_REQUESTED: 'user.email.verification.requested',
    TRANSACTION_CREATED: 'transaction.created',
    TRANSACTION_UPDATED: 'transaction.updated',
    TRANSACTION_DELETED: 'transaction.deleted',
    TRANSACTION_SUCCESSFUL: 'transaction.successful',
    TRANSACTION_FAILED: 'transaction.failed',
    TRANSACTION_REVERSED: 'transaction.reversed',
    WALLET_CREATED: 'wallet.created',
    WALLET_UPDATED: 'wallet.updated',
    WALLET_DELETED: 'wallet.deleted',
    WALLET_FUNDED: 'wallet.funded',
    WALLET_DEBITED: 'wallet.debited',
    WITHDRAWAL_SUCCESSFUL: 'withdrawal.successful',
    AIRTIME_PURCHASE: 'airtime.purchase',
    DATA_PURCHASE: 'data.purchase',
    PAYMENT_SUCCESS: 'payment.success',
}

module.exports = EVENTS